### ISSUE TITLE
Disk-related alerts duplicated if the same device is mounted multiple times

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-rancher-monitoring#14]
## Steps to Reproduce the Problem

On GKE, the same file system is bind-mounted in multiple places. If this devices runs full, an alert is create for EACH place where the device is mounted (up to 60).

In our case the following AlertRules were affected:
* NodeFilesystemSpaceFillingUp
* NodeFilesystemFilesFillingUp

However we assume that other AlertRules are affected as well.

## Actual Behavior

The same alert for the same block device is fired many times.

## Expected Behavior

Disk related alerts should be grouped by their `device` and `host_ip` (or `instance`) label.

**Comment by simu** [comment]
Deduplication can be implemented with `bottomk by (device, host_ip) (1, <expr>)` where `<expr>` is the original alert expression.
