### ISSUE TITLE
KubePersistentVolumeFillingUp duplicated

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-rancher-monitoring#16]
The alert is duplicated if the PV is remounted on a different server.

Full set of labels:

Label | Value
-- | --
Label Alertname | KubePersistentVolumeFillingUp
Label Cluster | c-fragrant-forest-8819
Label Cluster Name | xxx
Label Endpoint | https-metrics
Label Exported Namespace | xxx
Label Instance | 10.241.0.8:10250
Label Job | expose-kubelets-metrics
Label Namespace | cattle-prometheus
Label Node | aks-workers-20615988-vmss000014
Label Persistentvolumeclaim | nginx-php
Label Pod | prometheus-cluster-monitoring-0
Label Prometheus | cattle-prometheus/cluster-monitoring
Label Prometheus From | xxx
Label Service | expose-kubelets-metrics
Label Severity | critical
Label Tenant | t-ja3px4

## Actual Behavior
* An alert is fired for each host the PV is mounted on

## Expected Behavior
* Alerts are deduplicated based on PV

**Comment by simu** [comment]
Potentially we can build some complex query with metrics `kube_persistentvolumeclaim_info` and `kube_persistentvolume_info` to add labels for the underlying PV and storageclass to the `KubePersistentVolumeFillingUp` alerts.

Note that depending on the exact situation (e.g. PVs provisioned by nfs-client-provisioner), deduplicating on the PV won't be sufficient.
